version: '3.8'

services:
  # --- REDIS (Estado do Combate) ---
  redis:
    image: redis:alpine
    container_name: guildarena-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # --- REDIS INSIGHT (GUI para Redis) ---
  redis-insight:
    image: redis/redisinsight:latest
    container_name: guildarena-redis-insight
    restart: unless-stopped
    ports:
      - "5540:5540"
    depends_on:
      - redis

  # --- POSTGRES (Dados Persistentes: Players, Guilds) ---
  postgres:
    image: postgres:latest
    container_name: guildarena-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: GuildArenaDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql

  # --- PGADMIN (GUI para Postgres) ---
  pgadmin:
    image: dpage/pgadmin4
    container_name: guildarena-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@guildarena.com
      PGADMIN_DEFAULT_PASSWORD: password123
    ports:
      - "5050:80"
    depends_on:
      - postgres

volumes:
  redis_data:
  postgres_data: